/* 
**  mod_prometheus.c -- Apache sample prometheus module
**  [Autogenerated via ``apxs -n prometheus -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**	$ apxs -c -i mod_prometheus.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /prometheus in as follows:
**
**	#   apache2.conf
**	LoadModule prometheus_module modules/mod_prometheus.so
**	<Location /prometheus>
**	SetHandler prometheus
**	</Location>
**
**  Then after restarting Apache via
**
**	$ apachectl restart
**
**  you immediately can request the URL /prometheus and watch for the
**  output of this module. This can be achieved for instance via:
**
**	$ lynx -mime_header http://localhost/prometheus 
**
**  The output should be similar to the following one:
**
**	HTTP/1.1 200 OK
**	Date: Tue, 31 Mar 1998 14:42:22 GMT
**	Server: Apache/1.3.4 (Unix)
**	Connection: close
**	Content-Type: text/html
**  
**	The sample page from mod_prometheus.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "http_core.h"
#include "scoreboard.h"
#include "http_log.h"
#include "ap_config.h"
#include "ap_mpm.h"

static int server_limit, thread_limit, threads_per_child, max_servers, is_async;

#define KBYTE 1024

/* The sample content handler */
static int prometheus_handler(request_rec *r) {
	if (strcmp(r->handler, "prometheus")) {
		return DECLINED;
	}
	if (r->header_only) {
		return OK;
	}

	if (!ap_exists_scoreboard_image()) {
		ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r, APLOGNO(01237) "Prometheus status unavailable in inetd mode");
		return HTTP_INTERNAL_SERVER_ERROR;
	}

	r->allowed = (AP_METHOD_BIT << M_GET);
	if (r->method_number != M_GET)
		return DECLINED;

	int res;
    worker_score *ws_record;
	int counter_dead = 0;
	int counter_ready = 0;
	int counter_starting = 0;
	int counter_busy_read = 0;
	int counter_busy_write = 0;
	int counter_busy_keepalive = 0;
	int counter_busy_log = 0;
	int counter_busy_dns = 0;
	int counter_closing = 0;
	int counter_graceful = 0;
	int counter_idle_kill = 0;
	int counter_disabled = 0;

	for (int i = 0; i < server_limit; ++i) {
		for (int j = 0; j < thread_limit; ++j) {
			int indx = (i * thread_limit) + j;

			ws_record = ap_get_scoreboard_worker_from_indexes(i, j);
			res = ws_record->status;

			if ((i >= max_servers || j >= threads_per_child) && (res == SERVER_DEAD)) {
				counter_disabled++;
			} else {
				switch (res) {
                    case SERVER_READY:
						counter_ready++;
                        break;
                    case SERVER_STARTING:
						counter_starting++;
                        break;
                    case SERVER_BUSY_READ:
						counter_busy_read++;
                        break;
                    case SERVER_BUSY_WRITE:
						counter_busy_write++;
                        break;
                    case SERVER_BUSY_KEEPALIVE:
						counter_busy_keepalive++;
                        break;
                    case SERVER_BUSY_LOG:
						counter_busy_log++;
                        break;
                    case SERVER_BUSY_DNS:
						counter_busy_dns++;
                        break;
                    case SERVER_CLOSING:
						counter_closing++;
                        break;
                    case SERVER_DEAD:
						counter_dead++;
                        break;
                    case SERVER_GRACEFUL:
						counter_graceful++;
                        break;
                    case SERVER_IDLE_KILL:
						counter_idle_kill++;
                        break;
				}
			}
		}
	}

	r->content_type = "text/plain";
	char intconvbuf[20];

#define GAUGE(name,des,value) \
		snprintf(intconvbuf, sizeof(intconvbuf), "%d", (value) ); \
		ap_rputs(\
				"# HELP apache_thread_" name " " des "\n" \
				"# TYPE apache_thread_" name " gauge\n" \
				"apache_thread_" name " ", r); \
		ap_rputs(intconvbuf, r); \
		ap_rputs("\n", r)


	GAUGE("dead", "Killed", counter_dead);
	GAUGE("ready", "Open slot with no current process", counter_ready);
	GAUGE("starting", "Starting up", counter_starting);
	GAUGE("busy_read", "Reading Request", counter_busy_read);
	GAUGE("busy_write", "Sending Reply", counter_busy_write );
	GAUGE("busy_keepalive", "Keepalive (read)", counter_busy_keepalive);
	GAUGE("busy_log", "Logging", counter_busy_log);
	GAUGE("busy_dns", "DNS Lookup", counter_busy_dns);
	GAUGE("closing", "Closing connection", counter_closing);
	GAUGE("graceful", "Gracefully finishing", counter_graceful);
	GAUGE("idle_kill","Idle cleanup of worker",counter_idle_kill);	
	GAUGE("disabled", "Disabled", counter_disabled);


	return OK;
}

static int prometheus_init(apr_pool_t *p, apr_pool_t *plog, apr_pool_t *ptemp, server_rec *s)
{
	ap_mpm_query(AP_MPMQ_HARD_LIMIT_THREADS, &thread_limit);
	ap_mpm_query(AP_MPMQ_HARD_LIMIT_DAEMONS, &server_limit);
	ap_mpm_query(AP_MPMQ_MAX_THREADS, &threads_per_child);
	/* work around buggy MPMs */
	if (threads_per_child == 0)
		threads_per_child = 1;
	ap_mpm_query(AP_MPMQ_MAX_DAEMONS, &max_servers);
	ap_mpm_query(AP_MPMQ_IS_ASYNC, &is_async);
	return OK;
}


static void prometheus_register_hooks(apr_pool_t *p) {
	ap_hook_handler(prometheus_handler, NULL, NULL, APR_HOOK_MIDDLE);
	ap_hook_post_config(prometheus_init, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA prometheus_module = {
	STANDARD20_MODULE_STUFF, 
	NULL,						/* create per-dir	config structures  */
	NULL,						/* merge  per-dir	config structures  */
	NULL,						/* create per-server config structures */
	NULL,						/* merge  per-server config structures */
	NULL,						/* table of config file commands	   */
	prometheus_register_hooks	/* register hooks                      */
};

